/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Echarts: typeof import('./src/components/Echarts.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    File_upload: typeof import('./src/components/file_upload.vue')['default']
    OverTimeData: typeof import('./src/components/overTimeData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Web_Security: typeof import('./src/components/Web_Security.vue')['default']
    WebWorker: typeof import('./src/components/WebWorker.vue')['default']
  }
}
